//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Payments = new HashSet<Payment>();
            this.LogIns = new HashSet<LogIn>();
        }
    
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdentificationNumber { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public System.DateTime CreationTimeStamp { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual WorkoutProgram WorkoutProgram { get; set; }
        public virtual ICollection<LogIn> LogIns { get; set; }
    }
}
