//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public double Amount { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public string Comments { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
