//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutProgram
    {
        public WorkoutProgram()
        {
            this.Customers = new HashSet<Customer>();
            this.Workouts = new HashSet<Workout>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Workout> Workouts { get; set; }
    }
}
